export const GET_PHOTOS_START = 'GET_PHOTOS_START'
export const GET_PHOTOS_SUCCES = 'GET_PHOTOS_SUCCES'
export const GET_PHOTOS_FAILURE = 'GET_PHOTOS_FAILURE'

export const ADD_PHOTO_START = 'ADD_PHOTO_START'
export const ADD_PHOTO_SUCCES = 'ADD_PHOTO_SUCCES'
export const ADD_PHOTO_FAILURE = 'ADD_PHOTO_FAILURE'

export const SING_IN_START = 'SING_IN_START'
export const SING_IN_SUCCES = 'SING_IN_SUCCES'
export const SING_IN_FAILURE = 'SING_IN_FAILURE'

export const SING_UP_START = 'SING_UP_START'
export const SING_UP_SUCCES = 'SING_UP_SUCCES'
export const SING_UP_FAILURE = 'SING_UP_FAILURE'
// export const DOWNLOAD_PHOTO_START = 'DOWNLOAD_PHOTO_START'
// export const DOWNLOAD_PHOTO_SUCCES = 'DOWNLOAD_PHOTO_SUCCES'
// export const DOWNLOAD_PHOTO_FAILURE = 'DOWNLOAD_PHOTO_FAILURE'